apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vot
  name: vot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vot
    spec:
      containers:
      - image: schoolofdevops/vote:v1
        name: vote
        resources: {}
